[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
northfund = "EPGcFuarb1sqJPBMMrYwK6sbVArirhbwcpaXXY1816QZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.soo.network/rpc"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
