[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
northfund = "GzTAeUQX8Fdzyw99wEYC6iqY3bWKBPVgGftQeHM7D3YB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
